set(SOURCE_FILES
  include/glrt/scene/camera-component.h
  include/glrt/scene/camera-parameter.h
  include/glrt/scene/debug-camera.h
  include/glrt/scene/entity.h
  include/glrt/scene/light-component.h
  include/glrt/scene/material.h
  include/glrt/scene/scene.h
  include/glrt/scene/static-mesh-component.h
  src/glrt/scene/camera-component.cpp
  src/glrt/scene/camera-parameter.cpp
  src/glrt/scene/debug-camera.cpp
  src/glrt/scene/entity.cpp
  src/glrt/scene/light-component.cpp
  src/glrt/scene/material.cpp
  src/glrt/scene/scene.cpp
  src/glrt/scene/static-mesh-component.cpp
)
