set(SOURCE_FILES
  include/glrt/scene/camera-component.h
  include/glrt/scene/camera-parameter.h
  include/glrt/scene/debug-camera.h
  include/glrt/scene/entity.h
  include/glrt/scene/light-component.h
  include/glrt/scene/resources/asset-converter.h
  include/glrt/scene/resources/material-data.h
  include/glrt/scene/resources/resource-index.h
  include/glrt/scene/resources/resource-loader.h
  include/glrt/scene/resources/resource-uuid.h
  include/glrt/scene/resources/resource-uuid-index.inl
  include/glrt/scene/resources/resource-uuid.inl
  include/glrt/scene/resources/resource-uuid-loader.inl
  include/glrt/scene/resources/scene-loader.h
  include/glrt/scene/resources/static-mesh-data.h
  include/glrt/scene/scene.h
  include/glrt/scene/static-mesh-component.h
  src/glrt/scene/camera-component.cpp
  src/glrt/scene/camera-parameter.cpp
  src/glrt/scene/debug-camera.cpp
  src/glrt/scene/entity.cpp
  src/glrt/scene/light-component.cpp
  src/glrt/scene/resources/asset-converter.cpp
  src/glrt/scene/resources/resource-index.cpp
  src/glrt/scene/resources/resource-loader.cpp
  src/glrt/scene/resources/resource-uuid.cpp
  src/glrt/scene/resources/scene-loader.cpp
  src/glrt/scene/resources/static-mesh-data.cpp
  src/glrt/scene/scene.cpp
  src/glrt/scene/static-mesh-component.cpp
)
