set(SOURCE_FILES
  arrays/arrays-tests.cpp
  arrays/fragmented-array.test.cpp
  arrays/statespy.cpp
  arrays/statespy.h
  arrays/trait-handling.cpp
  coord-frame/coord-frame.cpp
  qt-tests/auto-disconnect-with-deletion.cpp
  qt-tests/auto-disconnect-with-deletion.h
  shader-includes/shader-includes.cpp
  shader-library/bvh.cpp
  shader-library/shader-library.cpp
)
