#ifndef GLRT_RENDERER_SURFACESHADERVISUALIZATIONS_H
#define GLRT_RENDERER_SURFACESHADERVISUALIZATIONS_H

#include <glrt/renderer/dependencies.h>

namespace glrt {
namespace renderer {


enum class SurfaceShaderVisualization
{
  NONE,
  AMBIENT_OCCLUSION,
  BVH_NEAREST_LEAF_INDEX_0,
  BVH_NEAREST_LEAF_INDEX_1,
  BVH_NEAREST_LEAF_INDEX_2,
  BVH_OCCLUSION_GRID,
  BVH_OCCLUSION_GRID_ONLY_0,
  BVH_OCCLUSION_GRID_ONLY_1,
  BVH_OCCLUSION_GRID_ONLY_2,
  CANDIDATE_GRID_NUM_STATIC_CANDIDATES,
  CANDIDATE_GRID_NUM_DYNAMIC_CANDIDATES,
  CASCADED_GRID_WEIGHTS,
  CASCADED_GRID_WEIGHTS_TINTED,
  DISTANCEFIELD_AO,
  DISTANCEFIELD_AO_COST_TEX,
  DISTANCEFIELD_AO_COST_CONE_SPHERE_INTERSECTION_TEST,
  DISTANCEFIELD_AO_COST_NUM_CONETRACED_SDF,
  DISTANCEFIELD_AO_COST_SDF_ARRAY_ACCESS,
  LIGHTING_FLAT,
  LIGHTING_ONLY,
  LIGHTING_ONLY_DIFFUSE,
  LIGHTING_ONLY_SPECULAR,
  LIGHTING_MIRROR_PERFECT,
  LIGHTING_MIRROR_ROUGH,
  LIGHTING_MIRROR_SMOOTH,
  LIGHTING_SILVER,
  MATERIAL_NORMAL_WS,
  MATERIAL_ALPHA,
  MATERIAL_ROUGHNESS_ADJUSTED,
  MATERIAL_ROUGHNESS_UNADJUSTED,
  MATERIAL_SMOOTHNESS,
  MATERIAL_BASE_COLOR,
  MATERIAL_METAL_MASK,
  MATERIAL_EMISSION,
  MATERIAL_REFLECTANCE,
  MATERIAL_OCCLUSION,
  MESH_NORMALS_WS,
  MESH_UVS,
  MESH_TANGENTS_WS,
  MESH_BITANGENTS_WS,
  SHOW_NAN,
  SHOW_INF,
  TEXTURE_BASECOLOR,
  TEXTURE_BASECOLOR_ALPHA,
  TEXTURE_NORMAL_LS,
  TEXTURE_BUMP,
  TEXTURE_SMOOTHENESS,
  TEXTURE_REFLECTIVITY,
  TEXTURE_METALLIC,
  TEXTURE_AO,
  TEXTURE_EMISSION,
};

extern SurfaceShaderVisualization currentSurfaceShaderVisualization;
QMap<QString, SurfaceShaderVisualization> allSurfaceShaderVisualizations();
void setCurrentSurfaceShaderVisualization(SurfaceShaderVisualization visualization);
extern bool show_forward_only;


} // namespace renderer
} // namespace glrt

#endif // GLRT_RENDERER_SURFACESHADERVISUALIZATIONS_H
