#define  VERTEX_ATTRIBUTE_LOCATION_POSITION 0
#define  VERTEX_ATTRIBUTE_LOCATION_NORMAL 1
#define  VERTEX_ATTRIBUTE_LOCATION_TANGENT 2
#define  VERTEX_ATTRIBUTE_LOCATION_UV 3

#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_POSITION 0
#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_PARAMETER1 1
#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_COLOR 2
#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_PARAMETER2 3

#define UNIFORM_BINDING_SCENE_BLOCK 0
#define UNIFORM_BINDING_MATERIAL_INSTANCE_BLOCK 1
#define UNIFORM_BINDING_MESH_INSTANCE_BLOCK  2

#define SHADERSTORAGE_BINDING_LIGHTS_SPHEREAREA 0
#define SHADERSTORAGE_BINDING_LIGHTS_RECTAREA 1

#define UNIFORM_BINDING_VALUE_PRINTER_BLOCK 15
#define SHADERSTORAGE_BINDING_VALUE_PRINTER 15
// FIXME is 15 really the best value?
