#define EXPECTED_GL_MAX_VERTEX_ATTRIB_BINDINGS 16
#define EXPECTED_GL_MAX_COMBINED_UNIFORM_BLOCKS 84
#define EXPECTED_GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS 96

#define  VERTEX_ATTRIBUTE_LOCATION_POSITION 0
#define  VERTEX_ATTRIBUTE_LOCATION_NORMAL 1
#define  VERTEX_ATTRIBUTE_LOCATION_TANGENT 2
#define  VERTEX_ATTRIBUTE_LOCATION_BITANGENT 3
#define  VERTEX_ATTRIBUTE_LOCATION_UV 4

#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_POSITION 0
#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_PARAMETER1 1
#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_COLOR 2
#define  DEBUG_MESH_VERTEX_ATTRIBUTE_LOCATION_PARAMETER2 3

// compute & vertex & fragment
#define UNIFORM_BINDING_SCENE_BLOCK 0

// compute only
#define UNIFORM_COLLECT_OCCLUSION_METADATA_BLOCK  1
#define UNIFORM_MERGE_SDF_BLOCK 1
#define IBL_BLOCK 1

// vertex & fragment
#define UNIFORM_BINDING_MATERIAL_INSTANCE_BLOCK  1

// vertex only
#define UNIFORM_BINDING_MESH_INSTANCE_BLOCK 2

// fragment only
#define UNIFORM_BINDING_DEBUG_POSTEFFECT_FRAGMENT 2
#define UNIFORM_BINDING_VALUE_PRINTER 3
#define UNIFORM_BINDING_POSTEFFECTVISUALIZATION_BLOCK 4
#define UNIFORM_BINDING_GBUFFER_BLOCK 5
