#define  VERTEX_ATTRIBUTE_LOCATION_POSITION 0
#define  VERTEX_ATTRIBUTE_LOCATION_NORMAL 1
#define  VERTEX_ATTRIBUTE_LOCATION_TANGENT 2
#define  VERTEX_ATTRIBUTE_LOCATION_UV 3

#define UNIFORM_BINDING_SCENE_BLOCK 0
#define UNIFORM_BINDING_MATERIAL_INSTANCE_BLOCK 1
#define UNIFORM_BINDING_MESH_INSTANCE_BLOCK  2
