set(SOURCE_FILES
  include/glrt/application.h
  include/glrt/gui/anttweakbar.h
  include/glrt/gui/toolbar.h
  include/glrt/renderer/debugging/debug-line-visualisation.h
  include/glrt/renderer/debugging/debug-mesh.h
  include/glrt/renderer/debugging/shader-debug-printer.h
  include/glrt/renderer/debugging/visualization-renderer.h
  include/glrt/renderer/declarations.h
  include/glrt/renderer/dependencies.h
  include/glrt/renderer/forward-renderer.h
  include/glrt/renderer/material-buffer.h
  include/glrt/renderer/sample-resource-manager.h
  include/glrt/renderer/scene-renderer.h
  include/glrt/renderer/static-mesh-buffer.h
  include/glrt/renderer/static-mesh-buffer-manager.cpp
  include/glrt/renderer/static-mesh-buffer-manager.h
  include/glrt/renderer/toolkit/aligned-vector.h
  include/glrt/renderer/toolkit/reloadable-shader.h
  include/glrt/renderer/toolkit/shader-compiler.h
  include/glrt/renderer/toolkit/shader-storage-format.h
  include/glrt/renderer/toolkit/temp-shader-file.h
  include/glrt/sample-application.h
  include/glrt/splashscreen-style.h
  include/glrt/system.h
  src/glrt/application.cpp
  src/glrt/gui/anttweakbar.cpp
  src/glrt/gui/toolbar.cpp
  src/glrt/renderer/debugging/debug-line-visualisation.cpp
  src/glrt/renderer/debugging/debug-mesh.cpp
  src/glrt/renderer/debugging/shader-debug-printer.cpp
  src/glrt/renderer/debugging/visualization-renderer.cpp
  src/glrt/renderer/forward-renderer.cpp
  src/glrt/renderer/material-buffer.cpp
  src/glrt/renderer/sample-application.cpp
  src/glrt/renderer/sample-resource-manager.cpp
  src/glrt/renderer/scene-renderer.cpp
  src/glrt/renderer/static-mesh-buffer.cpp
  src/glrt/renderer/toolkit/reloadable-shader.cpp
  src/glrt/renderer/toolkit/shader-compiler.cpp
  src/glrt/renderer/toolkit/temp-shader-file.cpp
  src/glrt/splashscreen-style.cpp
  src/glrt/system.cpp
)
