set(SOURCE_FILES
  include/glrt/application.h
  include/glrt/debug-camera.h
  include/glrt/debugging/debug-line-visualisation.h
  include/glrt/debugging/debug-mesh.h
  include/glrt/debugging/visualization-renderer.h
  include/glrt/dependencies.h
  include/glrt/gui/anttweakbar.h
  include/glrt/gui/toolbar.h
  include/glrt/profiler.h
  include/glrt/scene/camera-component.h
  include/glrt/scene/camera-parameter.h
  include/glrt/scene/entity.h
  include/glrt/scene/forward-renderer.h
  include/glrt/scene/light-component.h
  include/glrt/scene/material.h
  include/glrt/scene/scene.h
  include/glrt/scene/scene-renderer.h
  include/glrt/scene/static-mesh-component.h
  include/glrt/scene/static-mesh.h
  include/glrt/system.h
  include/glrt/toolkit/aligned-vector.h
  include/glrt/toolkit/assimp-glm-converter.h
  include/glrt/toolkit/geometry.h
  include/glrt/toolkit/json.h
  include/glrt/toolkit/shader-compiler.h
  include/glrt/toolkit/temp-shader-file.h
  src/glrt/application.cpp
  src/glrt/debug-camera.cpp
  src/glrt/debugging/debug-line-visualisation.cpp
  src/glrt/debugging/debug-mesh.cpp
  src/glrt/debugging/visualization-renderer.cpp
  src/glrt/dependencies.cpp
  src/glrt/gui/anttweakbar.cpp
  src/glrt/gui/toolbar.cpp
  src/glrt/profiler.cpp
  src/glrt/scene/camera-component.cpp
  src/glrt/scene/camera-parameter.cpp
  src/glrt/scene/entity.cpp
  src/glrt/scene/forward-renderer.cpp
  src/glrt/scene/light-component.cpp
  src/glrt/scene/material.cpp
  src/glrt/scene/scene.cpp
  src/glrt/scene/scene-renderer.cpp
  src/glrt/scene/static-mesh-component.cpp
  src/glrt/scene/static-mesh.cpp
  src/glrt/system.cpp
  src/glrt/toolkit/json.cpp
  src/glrt/toolkit/shader-compiler.cpp
  src/glrt/toolkit/temp-shader-file.cpp
)
