set(SOURCE_FILES
  include/glrt/dependencies.h
  include/glrt/toolkit/assimp-glm-converter.h
  include/glrt/toolkit/escape-string.h
  include/glrt/toolkit/geometry.h
  include/glrt/toolkit/json.h
  include/glrt/toolkit/podarray.h
  include/glrt/toolkit/podarray.inl
  include/glrt/toolkit/profiler.h
  include/glrt/toolkit/uuid.h
  include/glrt/toolkit/uuid.inl
  src/glrt/dependencies.cpp
  src/glrt/toolkit/escape-string.cpp
  src/glrt/toolkit/json.cpp
  src/glrt/toolkit/profiler.cpp
  src/glrt/toolkit/uuid.cpp
)
