set(SOURCE_FILES
  include/glrt/dependencies.h
  include/glrt/toolkit/array.h
  include/glrt/toolkit/array.inl
  include/glrt/toolkit/assimp-glm-converter.h
  include/glrt/toolkit/bit-magic.h
  include/glrt/toolkit/bit-magic.inl
  include/glrt/toolkit/concatenated-less-than.h
  include/glrt/toolkit/concatenated-less-than.inl
  include/glrt/toolkit/dependency-set.h
  include/glrt/toolkit/dependency-set.inl
  include/glrt/toolkit/escape-string.h
  include/glrt/toolkit/geometry.h
  include/glrt/toolkit/linked-tuple.h
  include/glrt/toolkit/logger.h
  include/glrt/toolkit/network.h
  include/glrt/toolkit/plain-old-data-stream.h
  include/glrt/toolkit/profiler.h
  include/glrt/toolkit/uuid.h
  include/glrt/toolkit/uuid.inl
  include/glrt/toolkit/zindex.h
  src/glrt/dependencies.cpp
  src/glrt/toolkit/escape-string.cpp
  src/glrt/toolkit/logger.cpp
  src/glrt/toolkit/network.cpp
  src/glrt/toolkit/plain-old-data-stream.cpp
  src/glrt/toolkit/profiler.cpp
  src/glrt/toolkit/uuid.cpp
  src/glrt/toolkit/zindex.cpp
)
