function(adapt_cmake_prefix_path ROOT)
  if(NOT ${ROOT} AND NOT $ENV{${ROOT}} STREQUAL "")
    set(${ROOT} $ENV{${ROOT}})
  endif()

  if(${ROOT})
    set(CMAKE_PREFIX_PATH_BACKUP ${${ROOT}} PARENT_SCOPE)
    set(CMAKE_PREFIX_PATH ${${ROOT}} PARENT_SCOPE)
  else()
    unset(CMAKE_PREFIX_PATH_BACKUP PARENT_SCOPE)
  endif()
endfunction()

function(reset_cmake_prefix_path)
  if(CMAKE_PREFIX_PATH_BACKUP)
    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH_BACKUP} PARENT_SCOPE)
      unset(CMAKE_PREFIX_PATH_BACKUP PARENT_SCOPE)
  endif()
endfunction()